CREATE DATABASE IF NOT EXISTS virtual_library;
USE virtual_library;
CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(150), email VARCHAR(255) UNIQUE, password VARCHAR(255), is_admin TINYINT(1) DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE books (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255), author VARCHAR(255), genre VARCHAR(100), filename VARCHAR(255), cover_filename VARCHAR(255), uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE reading_list (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT, book_id INT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE bookmarks (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT, book_id INT, page INT DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE reading_requests (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT, book_id INT, status ENUM('pending','approved','denied') DEFAULT 'pending', requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE notifications (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT, title VARCHAR(150), body TEXT, is_read TINYINT(1) DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
